name: Code quality check
on:
  push:
  merge:
  pull_request:
    branches: [dev, prod]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install
      - name: Run tests
        run: yarn test